build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.19
  amd64: ghcr.io/home-assistant/amd64-base:3.19
labels:
  org.opencontainers.image.title: "HA Joplin Bridge"
  org.opencontainers.image.description: "Bridge between Home Assistant and Joplin with Web Clipper API support"
  org.opencontainers.image.source: "https://github.com/Nab0y/hassio-addons"
  org.opencontainers.image.licenses: "MIT"
args:
  TEMPIO_VERSION: "2021.09.0"