name: "HA Joplin Bridge"
description: "Bridge between Home Assistant and Joplin with Web Clipper API support"
version: "1.0.8"
slug: ha-joplin-bridge
url: "https://github.com/Nab0y/hassio-addons/tree/main/ha-joplin-bridge"
arch:
  - aarch64
  - amd64
startup: services
boot: auto
init: false
hassio_api: true
hassio_role: default
homeassistant_api: false
host_network: false
map:
  - share:rw
ports:
  41185/tcp: 41185  
  41186/tcp: 41186
ports_description:
  41185/tcp: "Joplin Data API (Web Clipper)"
  41186/tcp: "Management API"
options:
  sync_target: 0
  sync_interval: 300
  locale: "en_GB"
  timezone: "UTC"
  enable_encryption: false
  encryption_password: ""
  sync_server_url: ""
  sync_username: ""
  sync_password: ""
schema:
  - name: sync_target
    type: list
    options: [0, 2, 3, 5, 7, 8, 9, 10]
    default: 0
  - name: sync_interval
    type: int
    default: 300
    min: 60
    max: 3600
  - name: locale
    type: str
    default: "en_GB"
  - name: timezone
    type: str
    default: "UTC"
  - name: enable_encryption
    type: bool
    default: false
  - name: encryption_password
    type: password
    optional: true
  - name: sync_server_url
    type: str
    optional: true
  - name: sync_username
    type: str
    optional: true
  - name: sync_password
    type: password
    optional: true
image: "ghcr.io/nab0y/{arch}-addon-ha-joplin-bridge"